name: Inline-MzScheme
version: 0.03
abstract: Inline module for the PLT MzScheme interpreter
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  Inline: 0.43
  Language::MzScheme: 0.03
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
